### ISSUE TITLE
Shield sum uses ATH instead of KKR

### ISSUE THREAD

**Issue by opatut** [Gorthian/HeXXen1733_Custom_Character_Sheet#19]
Book says its KKR, this line uses ATH instead:

https://github.com/Gorthian/HeXXen1733_Custom_Character_Sheet/blob/eb28ebfc40cf1d0fd3d0e9744ec113f7adb8ae11/HeXXen1733_by_Gorthian.html#L2105

**Comment by Gorthian** [comment]
Fixed in Branch Bugfixes

**Comment by Gorthian** [comment]
Fixed in Branch Main
