### ISSUE TITLE
Konstruktionspunkte werden nicht gespeichert

### ISSUE THREAD

**Issue by opatut** [Gorthian/HeXXen1733_Custom_Character_Sheet#24]
* Character sheet öffnen
* Auf _Besitz_ wechseln
* KP eintragen
* Character sheet schließen
* Character sheet öffnen
* Auf _Besitz_ wechseln
* KP sind leer

**Comment by Gorthian** [comment]
Nutzt ihr schon die aktuellste Version?
Das sollte nämlich bereits behoben sein:
Siehe hier: #22

**Comment by opatut** [comment]
Bei meinem Char in "About" steht version 1.3, aber wir haben schon den Schildbenutzungs-Fix von 2.0.1 drin. Ich bin verwirrt :D

**Comment by Gorthian** [comment]
Ja, ich muss zu meiner Schande gestehen, dass ich die Versionsnummer bei About ständig vergesse anzupassen.

Schau mal direkt in den ersten Zeilen der HTML-Datei nach der Version.
Ganz aktuell inkl. KP-Fix müsste die 2.0.2 sein.

**Comment by opatut** [comment]
![image](https://user-images.githubusercontent.com/235784/111037097-ecb56f00-8422-11eb-87f4-745a13643739.png)

Das hier?

**Comment by opatut** [comment]
Ja okay auf jeden Fall steht noch der "KP" placeholder drin, also haben wir den fix noch nicht. Ich weiß nicht wie ich das genauer nachschaue, ich bin nicht HeXXenmeister*in ;) Aber ich habe unsere*n darauf hingewiesen dass es gefiXXt ist :)

**Comment by Gorthian** [comment]
Zeile 3 und 4 ist da am aussagekräftigsten.
Ich versuche aber auch mehr an die Versiosnummer im "About" zu denken.

![grafik](https://user-images.githubusercontent.com/74892068/111039318-b0d3d700-842d-11eb-8708-224dc84b0e2a.png)
