### ISSUE TITLE
Fehlende Zustände

### ISSUE THREAD

**Issue by opatut** [Gorthian/HeXXen1733_Custom_Character_Sheet#25]
Im Regelwerk auf Seite 75ff. gibt es noch folgende 3 Zustände, die nicht in der Zustandstabelle aufgeführt sind:

* Erfrierung 
* Stummheit 
* Vergiftung

**Comment by Gorthian** [comment]
Gefühlt bringt jedes Abenteuer und jeder Boss-Gegner neue Zustände mit. Das Regelwiki listet aktuell mehr als 30 Zustände.
Ich bin mir daher noch unschlüssig ob es Sinn macht die alle mit aufzunehmen.

**Comment by Gorthian** [comment]
Siehe auch hier:
#26 
#27
