### ISSUE TITLE
Rolling without queries and adding/substracting Janus dice

### ISSUE THREAD

**Issue by runeb68** [Gorthian/HeXXen1733_Custom_Character_Sheet#28]
Moin

Ich fände es gut wenn man die Abfrage zur Anzahl der Januswürfel abschalten könnte und die Januswürfel addiert würden. Einige Sheets anderer Systeme (z.B. Cypher) haben dafür eine Checkbox. Wenn ich nicht per Macro von der Karte würfle sondern vom Charakterbogen finde ich die Abfrageboxen besonders störend wenn man den Bogen in einem eigenen Fenster hat weil sie weiterhin im Kartenfenster aufpoppen.

Für meine Runde habe ich folgende Änderungen gemacht (Code folgt weiter unten):

∙ Rollstring:  "t[@{tblHexxen}]+1*@{JanusCalc}t[@{tblJanus}]"
∙ Codeänderung: Positiv machen entfernt und zweites "if" um Werte < -5 auf -5 zu begrenzen

Das "1*" kann man auch weglassen. Mit "1*" funktioniert statt z.B. statt "3" auch "+3".
(++ ist ein Fehler, +- geht).
Merkwürdig ist das vor einem Tabellenwurf nur eine Zahl geht, kein Ausdruck. Ich hatte erst mit Formeln und "abs()" experimentiert weil ich dachte das der Wert nicht negativ werden darf. Es scheint aber das Roll20 ggf. das Minus erst hinterher beachtet. Vielleicht ändern sie diese Merkwürdigkeiten irgendwann mal...

Gobale Ersetzung:
```
<     \n/r (?{Anzahl Janus?|@{JanusCalc}})t[@{tblJanus}]
>    +1*@{JanusCalc}t[@{tblJanus}]
```

Code Änderung: (diff, Zeilennummern noch Version 1.3)
```
1438,1444c1438,1446
< 			if (JanusCalc < 0 ) {
< 				JanusText = "gegen Dich";
< 				JanusCalc = JanusCalc * -1;
< 			} else {
< 				JanusText = "für Dich"
< 			}
< 			if (JanusCalc > 5) JanusCalc = 5;
---
> 			if (JanusCalc < 0 ) {
>                                 JanusText = "gegen Dich";
>                                 /* JanusCalc = JanusCalc * -1;*/
>                         } else {
>                                 JanusText = "für Dich"
>                         }
>                         if (JanusCalc > 5) JanusCalc =  5;
>                         if (JanusCalc < -5) JanusCalc = -5;
> 
```

Im Kartenfenster habe ich für alle global als Token Action und für den SL Macrobuttons definiert. Einen mit Popup für HeXXenwürfel, einen für den Initiativtracker und fünf für 1-5 Januswürfel. So kann man sie bei Bedarf immer nachwürfeln wenn man vergessen hat sie einzustellen.

Gruß, Rune B.

**Comment by Gorthian** [comment]
**Abstellbare Januswürfel**

Ich habe leider noch keine Möglichkeit gefunden innerhalb des Rollbuttons eine eine IF-Abfrage zu implementieren, die eine solche Checkbox abfragen könnte. Falls Dir dafür eine Lösung bekannt ist, immer her damit.

**Makros**

Entsprechende globale Makros stelle ich meinen Spielern in der Regel auch zur Verfügung.
Hier würde ich mir von Roll20 eine Möglichkeit wünschen solche Makros auch schon über den Code des Charaktersheets zu definieren. Das scheint leider nicht zu funktionieren.

**Nachwürfeln**

Dafür wurde mit v1.3 in der rechten Spalte die Möglichkeit eingeführt jede Art von Würfel direkt aus dem Sheet heraus zu würfeln.
Nur für den Fall, dass ihr die entsprechenden Buttons bisher evtl. übersehen habt.

**die lästigen Eingabefelder**

Nerven mich ebenfalls. Leider habe ich keinerlei Chance zu beeinflussen wo diese erscheinen.
Mit Wegfall der Januseingabe wäre das tatsächlich einfacher.
Das scheitert aber aktuell an meiner oben beschriebenen Unfähigkeit eine IF-Abfrage direkt im Würfelbefehl unterzubringen.

**Comment by runeb68** [comment]
Beispiel für konfigurierbare Bögen: 

Bei dem Cypher Character Sheet kann man das Abfragen umschalten.
Es gibt 2 Versionen wobei eine wohl älter aber übersichtlicher ist:
  https://github.com/Roll20/roll20-character-sheets/tree/master/CypherSystem  (älter, kürzer, übersichtlicher)
  https://github.com/Roll20/roll20-character-sheets/tree/master/Cypher%20Systems%20by%20Roll20

Ansonsten besteht natürlich für diejenigen die es direkt gewürfelt und  / oder addiert haben wollen die Möglichkeit meinen Änderungsvorschlag zu übernehmen und bei Bedarf nachzuwürfeln.

Grundsätzlich könne man die Rollstrings auch in Variable (Attribute) tun, das ist zumindest bei der manuellen Eingabe unangenehm wegen der nötigen ESC-Strings bei verschachtelten Roll-Macros. Sollte aber im Bogen aus dem Code heraus gut funktionieren wenn da nicht die table rolls spinnen - ich habe es hier noch nicht probiert. Wenns klappt bräuchte man den Rollstring auch nur an einer Stelle zu ändern statt mit "Suchen und Ersetzen" zu arbeiten.

**Comment by Gorthian** [comment]
Der Weg über die Attribute kam mir in dem Zusammenhang tatsächlich noch nicht in den Sinn.

Das werde ich mir auf jeden Fall nochmal genauer ansehen.

Danke für die Links.

**Comment by Gorthian** [comment]
Über Hilfe & Einstellungen lassen sich ab v2.1.1 die berechneten Januswürfel automatisch in die Probe übernehmen.

**Comment by Gorthian** [comment]
Versehentlich geschlossen,  statt nur zu kommentieren.

**Comment by Gorthian** [comment]
Ich hatte gehofft beide Optionen getrennt voneinander realisieren zu können.

An der manuellen Eingabe von Januswürfeln in Kombination mit der Verrechnung von Erfolgen und Jansusymbolen bin ich aber gescheitert. Eingaben von negativen Werten werdet die Würfeltabelle dahinter nicht aus.

Also doch "nur" zwei Checkboxen, bei denen die Option der Ergebnissberechnung die automatische Übernahme der Anzahl an Januswürfeln bedingt.

Ich bin nicht hunderprozentig glücklich damit, aber Dein Vorschlag sollte sich damit abdecken lassen.

**Comment by runeb68** [comment]
Danke für die Umsetzung!

Mir gefällt der Bogen und das Engagement sehr. Ich habe mich bisher mit Lob zurückgehalten weil ich eigentlich ein Bug / Feature Request System nicht als Diskussionsforum empfinde und daher eher sachlich bleibe...

**Comment by runeb68** [comment]
Ich experimentiere gerade damit. 

Vielleicht geht es ja ohne die runden Klammern:
`rollJanus = "?{Anzahl Janus?|@{JanusCalc}}t[@{tblJanus}]";`

Ich schaue auch JanusCalc je nach Checkboxstatus neu zu berechnen.
Wenn es bei mir sauber läuft melde ich die Änderungen.

**Comment by runeb68** [comment]
So, ohne Klammern in rollJanus auch bei Wurf mit Popup für die Januswürfel-Zahl geht es.
Ausserdem habe ich ergänzt das JanusCalc beim Addieren bei Malus negativ ist und sonst positiv.
Wenn berücksichtig werden soll das eventuell jemand "+3" statt "3" in die Janusbox tippt sollte "+1*" statt "+" als RollSeperator verwendet werden. 

Ansonsten schlage ich zur Klarstellung vor "Januswürfel addieren" statt "Automatische Ergebnisberechnung" zu schreiben, dann kann man das besser auseinanderhalten. Der Text "Bedingt die "Automatische Janusberechnung"" ist nun nicht mehr nötig. Ich würde statt "Automatische Janusberechnung" auch "Januswurf ohne Rückfrage" schreiben. Ausser es fallen Dir noch klarere Texte ein.

Im Folgenden die beiden Funktionen wie sie bei mir nun laufen:

```
/* Automatische Berechnung der Januswürfel aktivieren/deaktivieren */
	on("sheet:opened change:JanusAutoCalc change:SumAutoCalc", function() {
		getAttrs(["JanusAutoCalc","SumAutoCalc","JanusCalc","JanusText"], function (values) {
			let JanusAutoCalc = values.JanusAutoCalc;
			let SumAutoCalc = values.SumAutoCalc;
			let JanusCalc = parseInt(values.JanusCalc); 
			let JanusText = values.JanusText;
			let rollJanus = "";
			let rollSeperator = "";
						
			if (JanusCalc < 0) { JanusCalc = JanusCalc * -1; } /* oder Math.abs() - positiv vorbelegen */
				
			/* Automatisch oder soll beim Würfeln jedesmal nach der Anzahl der Januswürfel gefragt werden */
			if (JanusAutoCalc === "1"){
				rollJanus = "@{JanusCalc}t[@{tblJanus}]";
			} else {
				rollJanus = "?{Anzahl Janus?|@{JanusCalc}}t[@{tblJanus}]";
			}
			
			if (SumAutoCalc === "1"){
				rollSeperator = "+"; /* Januswürfel werden addiert */
				if(JanusText === "Malus") /* muss gleicher Text wie in nächster Funktion sein */
				{
					JanusCalc = JanusCalc * -1; /* Januswurf wird abgezogen (negativ addiert) */
				}
			} else {
				rollSeperator = "\n/r "; /* 2 getrennte Würfe, Januswürfelzahl immer Positiv */
			}
			
			setAttrs({			
				"rollJanus": rollJanus,
				"rollSeperator": rollSeperator,
				"JanusAutoCalc": JanusAutoCalc,
				"SumAutoCalc": SumAutoCalc,
				"JanusCalc": JanusCalc
			});
		});
	});
	
	/* Januspool berechnen */
	on("sheet:opened change:influenceMalusLevel change:MalusMod change:Bonusesidious change:BonusFocused change:BonusMod", function() {
		getAttrs(["influenceMalusLevel","MalusMod","Bonusesidious","BonusFocused","BonusMod","SumAutoCalc"], function (values) {
			let influenceMalusLevel = parseInt(values.influenceMalusLevel)||0;
			let MalusMod = parseInt(values.MalusMod)||0;
			let Bonusesidious = parseInt(values.Bonusesidious)||0;
			let BonusFocused = parseInt(values.BonusFocused)||0;
			let BonusMod = parseInt(values.BonusMod)||0;
			let SumAutoCalc = values.SumAutoCalc;
			let JanusCalc = 0;
			let JanusText = "";
			
			/* warum hier hinter dem "=" nochmal JanusCalc was ja hier vorher immer null ist? */
			JanusCalc = JanusCalc - influenceMalusLevel - MalusMod + Bonusesidious + BonusFocused + BonusMod;
			
			if (JanusCalc < 0 ) {
				JanusText = "Malus"; /* wenn Text hier geändert wird auch in vorheriger Funktion anpassen! */
				if (SumAutoCalc === "0"){
					JanusCalc = JanusCalc * -1; /* Positiv machen wenn nicht addiert wird */
				}
			} else {
				JanusText = "Bonus"
			}
			if (JanusCalc > 5) JanusCalc = 5;
			if (JanusCalc < -5) JanusCalc = -5;
			
			setAttrs({
				"JanusCalc"	: JanusCalc,
				"JanusText" : JanusText
			});
		});
	});

```
Ich hoffe die Abfrage des Wortes "Malus" kollidiert nicht mit den Sprachdateien... Sonst bräuchte es noch eine Variable.

Es hat eine Weile gedauert herauszufinden das ich nicht abs() einfach so verwenden kann und deshalb bei meinen Tests die eine Funktion teils oder ganz nicht ausgeführt wurde. Math.abs() geht. Weitere Suche hat mich darauf gestossen das Fehler ggf. in der Debugconsole des Browsers auftauchen und nicht nirgendwo oder bei Roll20 irgendwo.
Ich habe schließlich trotzdem wieder die "if(x<0) x=x*-1" statt "let x=Math.abs(parseInt(values.x))" genommen.

P.S. Meine Rechtschreibprüfung hätte lieber Separator statt Seperator, schreibe ich auch meistens so bis es rot unterstrichen wird ;)

**Comment by Gorthian** [comment]
Vielen Dank für die Mühe.
Ich spiele Deine Änderungen bei Gelegenheit in meine aktuelle Version und teste auch nochmal.

Es kann diesmal aber ein paar Tage dauern.

**Comment by Gorthian** [comment]
Die vorgeschlagenen Änderungen sind in v2.1.3 eingespielt.
