### ISSUE TITLE
Januswürfel addieren statt sie separat zu würfeln

### ISSUE THREAD

**Issue by runeb68** [Gorthian/HeXXen1733_Custom_Character_Sheet#30]
Moin

In Issue #28 bereits mit Codeänderung und Würfelstring für Wurf ohne Abfrage für die alte Version vorgeschlagen.

∙ Den Wertebereich der Januswürfel von -5 bis +5 zulassen

∙ addieren: Statt Neue Zeile und neues /r einfach "+" oder "+1*". Die Klammer muß entfernt werden.
```
< "/me würfelt auf Heimlichkeit\n/r (@{StealthMod})t[@{tblHexxen}]\n/r (@{rollJanus})" 
> "/me würfelt auf Heimlichkeit\n/r (@{StealthMod})t[@{tblHexxen}]+@{rollJanus}" 
```
![image](https://user-images.githubusercontent.com/78030873/112234552-0d5ca080-8c3d-11eb-9209-aeec10f0959a.png)

∙ Optional: Darstellung in der ersten Zeile des Bogens anpassen wenn es stört das es nun negativ werden kann
![Ohne Titel](https://user-images.githubusercontent.com/78030873/112235195-6f69d580-8c3e-11eb-9956-7892c5c0ed5b.png)

∙ wenn es vielleicht nicht jedem gefällt auch konfigurierbar machen? Der String "\n/r " oder "+" kann auch in einem Attribut abgelegt werden.

Vorteile: kompaktere Darstellung, Endwert gleich ablesbar (wenn keine Fertigkeit die Espritsterne aufwertet).
Nachteile: Alle Würfel hintereinander, ohne weitere Codeänderung Anzeige von "-x gegen Dich" im Bogen.

Gruß, Rune.

**Comment by Gorthian** [comment]
Duplikat von #28

Wurde versehentlich zu früh geschlossen.
