### ISSUE TITLE
Bei neuem Charakter erscheint kein Tabreiter

### ISSUE THREAD

**Issue by runeb68** [Gorthian/HeXXen1733_Custom_Character_Sheet#35]
Ursachen:
 - Die on sheet:opened Funktion /* Standardwerte für Würfeltabellen und Attribute setzen */ setzt den Wert nur wenn er noch nicht gesetzt ist ("general").
 - im HTML ist der angegebene Wert  'character' und eine solche Seite des Charakterbogens existiert nicht (ca. Zeile 140-150)

Vorschlag: 
  im HTML weglassen (er würde ja bereits in der Funktion gesetzt) oder gültigen Wert im HTML angeben (dann ist das Setzen in der Funktion nicht mehr nötig)

Ich meine das es eine Überlegung Wert wäre beim ersten Öffnen die Einstellungsseite zu zeigen (attr_sheetTab = "help").
  Ich habe bei mir gleich Werte für alle Tabellen dort vorbelegt...  (Blut, Segnung, Elixir) und die Checkboxen ggf. mit dem Attribut checked versehen.   amit wäre das Bearbeiten der Seite nicht unbedingt nötig da alles ausgefüllt ist.

Man könnte die ganze Funktion für die Standardwerte weglassen wenn alles im HTML vorbelegt wird oder umgekehrt alles in der Funktion setzten.

**Comment by Gorthian** [comment]
Mit einer echten Vorbelegung der Standarwerte tue ich mir schwer, da hier die Präferenzen je Gruppe doch stark abweichen können.

Aber vielleciht lässt sich das über ein API-Skript realisieren, dass immer beim Erstellen einen neuen Characters die gleichen Werte setzt: https://app.roll20.net/forum/post/8556225/how-to-set-default-sheet-attributes

**Comment by Gorthian** [comment]
In den Branches **Main** und **Mare Monstrum" korrigiert.
Die Idee von generellen Standardwerten hierher ausgelagert: #40
