### ISSUE TITLE
Neue Zustände sind nicht angekreuzt

### ISSUE THREAD

**Issue by runeb68** [Gorthian/HeXXen1733_Custom_Character_Sheet#36]
In der Funktion zum Anlegen der Zustandseinträge wird das Feld attr_condition_isActive auf angekreuzt gesetzt. Das funktioniert nicht weil in repeating Bereichen die Angabe value="1" fehlt weshalb die Box den Wert "on" hätte wenn sie angekreuzt wäre.

**Comment by Gorthian** [comment]
In den Branches **Main** und **Mare Monstrum** korrigiert
