### ISSUE TITLE
Standardwerte für neue Charaktere

### ISSUE THREAD

**Issue by Gorthian** [Gorthian/HeXXen1733_Custom_Character_Sheet#40]
Kann man z.B. über ein optionales API-Skript und dem "on(add:character) event" Standarwerte für Würfeltabellen, Einstellungen & Co mitgeben?

Dann könnt der Spielleiter seine präferierten Werte dort zentral konfigurieren.

**Comment by runeb68** [comment]
Ich habe gelesen das Variable in Charaktersheets global über alle Bögen sind. Also vermutlich dann wenn sie ausserhalb von lokalen Gültigbereichen stehen.  Oder "static" sind wenn es das in JS gibt.
Möglicherweise gehen sie aber verloren wenn die Sitzung geschlossen wird und gelten nur in dem Browser des jeweiligen Nutzers.

Wenn also der erste einen Bogen öffnet könnte man die Werte dieses Bogens in Variable packen und wenn andere Bögen (nur im gleichen Browser auf dem gleichen Rechner?) feststellen das sie bereits gesetzt sind können diese die als Default übernehmen. 

Das würde bedeuten das man vor dem Anlegen neuer Chars dann einfach einen vorhandenen mit den gewünschten Standardwerten öffnet. Wenn entsprechende Tests aufgrund dieser Infos erfolgreich sind, bräuchte man kein extra API Script dafür.

... mal sehen wer von uns das zuerst testet ;-)

**Comment by Gorthian** [comment]
Erster ;-)

Ich spiele das API-Skript jetzt aber erstmal nur im Branch **Mare Monstrum** ein, und teste da noch eine Weile.

**Comment by Gorthian** [comment]
Die API für Standardwerte ist im Main-Branch angekommen
